{
 "title": "Data Miner Job",
 "tags": [
  "batch",
  "data-miner"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Job Duration",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mining_duration_seconds" }
   ]
  },
  {
   "title": "Data Download Duration",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "data_download_seconds" }
   ]
  },
  {
   "title": "Last Execution",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "time() - mining_last_run" }
   ]
  },
  {
   "title": "Vehicle Telemetry Extraction",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "record_extraction_seconds_sum  "
    }
   ]
  },
  {
   "title": "Job Exceptions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "exceptions_total" }
   ]
  },
  {
   "title": "Telemetry Push Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "telemetry_server_push_seconds_sum"
    }
   ]
  },
  {
   "title": "Vehicle Data Extraction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "record_count_total", "legendFormat": "found-{{job}}" },
    {
     "expr": " (record_count_total - records_extracted_failed_total)",
     "legendFormat": "extraced-{{job}}"
    },
    { "expr": "records_extracted_failed_total", "legendFormat": "failed-{{job}}" }
   ]
  },
  {
   "title": "Vehicles Failed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "record_count_total", "legendFormat": "vehicles" },
    {
     "expr": " (record_count_total - records_extracted_failed_total)",
     "legendFormat": "extracted"
    },
    { "expr": "records_extracted_failed_total", "legendFormat": "failed" }
   ]
  },
  {
   "title": "Telemetry Push Attempts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "telmetry_push_attempts_total", "legendFormat": "attempts" },
    {
     "expr": "(record_count_total - records_sent_failed_total)",
     "legendFormat": "successful"
    },
    { "expr": "records_sent_failed_total", "legendFormat": "errors" }
   ]
  },
  {
   "title": "Telemetry Push Attempts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "telmetry_push_attempts_total", "legendFormat": "attempts" },
    {
     "expr": "(record_count_total - records_sent_failed_total)",
     "legendFormat": "successful"
    },
    { "expr": "records_sent_failed_total", "legendFormat": "errors" }
   ]
  },
  {
   "title": "Job Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{namespace=\"omnifleet\", job=\"omnifleet/king-county-telemetry-miner\"} | json | line_format \"{{.asctime}}: {{.levelname}} - {{.message}}\""
    }
   ]
  }
 ]
}